module.exports = Object.freeze({
    INPUT_ORIENTATION: {
        VERTICAL: "Vertical",
        HORIZONTAL: "Horizontal"
    },
    INPUT_SIZE: {
        SMALL: "Small",
        LARGE: "Large"
    },
    ROLES: {
        USER: 'User',
        ADMIN: 'Admin',
        MODERATOR: 'Moderator'
    },
    YEAR_OFFSET: 14,
    YEAR_LIMIT: 80,
    FIRST_DAY: 1,
    LAST_DAY: 31,
    PASSWORD_LENGTH: 5,
    GENDER_OPTIONS: [
        {value: ''},
        {value: 'Hombre'},
        {value: 'Mujer'},
    ],
    PURPOSE_OPTIONS: [
        {value: ''},
        {value: 'Pajera'},
        {value: 'Amigos'},
        {value: 'Chatear'},
    ],
    AGE_OPTIONS: [
        {value: ''},
        {value: '18 y 24 años'},
        {value: '25 y 31 años'},
        {value: '32 y 38 años'},
        {value: '39 y 45 años'},
        {value: '46 y 52 años'},
        {value: '53 años y más'},
    ],
    REGION_OPTIONS:  [
        {value: ''},
        {value: '1 Region'},
        {value: '2 Region'},
        {value: '3 Region'},
        {value: '4 Region'},
        {value: '5 Region'},
    ],
    EDUCATION_OPTIONS: [
        {value: ''},
        {value: 'Basica'},
        {value: 'Media'},
        {value: 'Tecnica'},
        {value: 'Universitaria'},
        {value: 'Post grado'},
        {value: 'Otro'},
    ],
    COMMUNE_OPTIONS:  [
        {value: ''},
        {value: 'ANTOFAGASTA'},
        {value: 'CALAMA'},
        {value: 'MARIA ELENA'},
        {value: 'MEJILLONES'},
        {value: 'OLLAGUE'},
        {value: 'SAN PEDRO DE ATACAMA'},
        {value: 'SIERA GORDA'},
        {value: 'TALTAL'},
        {value: 'TOCOPILLA'},
    ],
    CHILDREN_OPTIONS:  [
        {value: ''},
        {value: 'Si, en casa'},
        {value: 'Si'},
        {value: 'De visita'},
        {value: 'No'},
    ],
    MONTH_OPTIONS: [
        {value: ''},
        {value: 1, text: 'Enero'},
        {value: 2, text: 'Febrero'},
        {value: 3, text: 'Marzo'},
        {value: 4, text: 'Abril'},
        {value: 5, text: 'Mayo'},
        {value: 6, text: 'Junio'},
        {value: 7, text: 'Julio'},
        {value: 8, text: 'Agosto'},
        {value: 9, text: 'Septiembre'},
        {value: 10, text: 'Octubre'},
        {value: 11, text: 'Noviembre'},
        {value: 12, text: 'Diciembre'}],
});
