export default {
  USER_REGISTRATION_SET_OVERVIEW: "REGISTRATION_SET_OVERVIEW",
  USER_REGISTRATION: "REGISTRATION",
  USER_LOGIN: "LOGIN",
  USER_REQUEST: "USER_REQUEST",
  USER_RESPONSE: "USER_RESPONSE",
  USER_ERROR: "USER_ERROR",

  UTILITY_TOGGLE_SIGN_IN: "UTILITY_TOGGLE_SIGN_IN"
};
